namespace ConsoleSpinner
{
    public enum SpinnerType
    {
        OneDot,
        OneDotReverse,
        TwoDot,
        TwoDotReverse,
        ThreeDot,
        ThreeDotReverse,
        FourDot,
        FourDotReverse,
        FiveDot,
        FiveDotReverse,
        SixDot,
        SixDotReverse,
        SevenDot,
        SevenDotReverse,
        OneDotSnake,
        TwoDotSnake,
        InverseOneDotSnake,
        InverseTwoDotSnake,
        AlternatingX,
        AlternatingCorners,
        RotatingCorners,
        RotatingCornersReverse,
        PulsingCorners,
        PulsingBox,
        Blinking
    }
}
